### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by organicnz** [mansueli/Supa-Migrate#4]
Hi Rodrigo,

I hope everything is going well for you :)
Apologies for the feature request, mate. Could we, by any chance, improve these actions on GitHub to be able to commit the dump.sql file automatically? It doesn't push the dump at this stage hehe :)

Thanks so much :)

GitHub workflow file: `.github/workflows/main.yml`

```
# This is a basic workflow to help you get started with Actions

name: DB backup

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:   
   run_db_backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script file
        run: |
           chmod +x ./backup_database.sh
           ./backup_database.sh
        shell: bash   
      
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Results from R script" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
```

**Comment by mansueli** [comment]
Sorry for the delay, I never used GitHub actions before. But I got his working with the code below:

## Requiments:

Set the following secrets in the repo:
 - `SUPABASE_URL `
 - `SUPABASE_PASSWORD`

Source of the action:
`.github/workflows/main.yml`

````
name: Supa-backup
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:   
 run_db_backup:
  runs-on: ubuntu-latest
  permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
  steps:
     - uses: actions/checkout@v3
       with:
         ref: ${{ github.head_ref }}
     - name: Postgres15 
       run: |
         sudo apt-get remove postgresql-client-common
         sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
         wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo tee /etc/apt/trusted.gpg.d/pgdg.asc &>/dev/null
         sudo apt update
         sudo apt install postgresql-15 postgresql-client-15 -y
         /usr/lib/postgresql/15/bin/pg_dump --clean --if-exists --quote-all-identifiers --schema '*' --exclude-schema 'extensions|graphql|graphql_public|net|pgbouncer|pgsodium|pgsodium_masks|realtime|supabase_functions|storage|pg_*|information_schema' -d postgres://postgres:${{ secrets.SUPABASE_PASSWORD }}@${{ secrets.SUPABASE_URL }}:6543/postgres > dump.sql
         
     - name: Tweaking the dump file    
       run: |
         sed -i -e 's/^DROP SCHEMA IF EXISTS "auth";$/-- DROP SCHEMA IF EXISTS "auth";/' dump.sql
         sed -i -e 's/^DROP SCHEMA IF EXISTS "storage";$/-- DROP SCHEMA IF EXISTS "storage";/' dump.sql
         sed -i -e 's/^CREATE SCHEMA "auth";$/-- CREATE SCHEMA "auth";/' dump.sql
         sed -i -e 's/^CREATE SCHEMA "storage";$/-- CREATE SCHEMA "storage";/' dump.sql
         sed -i -e 's/^ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin"/-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin"/' dump.sql
       shell: bash   

     - uses: stefanzweifel/git-auto-commit-action@v4
       with:
         commit_message: Supabase backup
````
I'll check if I am able to put this on the GitHub marketplace, but I hope this helps.

**Comment by mansueli** [comment]
I've given it a shot, probably not great 😅 , but it might help.

https://github.com/mansueli/Supa-Backup

But I wasn't able to figure out how to pass the `${{secrets.SUPABASE_URL}}` & `${{secrets.PASSWORD}}` there in the action. So, I've also set the workflow above in the main repo. 

If you know a way around this, please share. 

Thanks!

**Comment by bokub** [comment]
You can also save the dump as an Action artifact instead of creating a commit (so you can manage retention & avoid making your repository bigger at every backup).

![image](https://user-images.githubusercontent.com/17952318/228242678-641ff4f9-b58b-437a-9cde-46a1569fe9d4.png)


Just add this at the end of the steps:

```yaml
      - uses: actions/upload-artifact@v2
        name: Save backup as artifact
        with:
          name: Backup
          path: /tmp/supabase_backup
          retention-days: 14
```
